Add exclude folders option
storyblok/storyblok pull request #723
Opened 2021-10-30 12:17 UTC by goran1023

2022-10-06 17:51 UTC, ademarCardoso commented on src/tasks/sync.js
> +    var _targetFolders = await this.client.getAll(`spaces/${this.targetSpaceId}/stories`, {
```suggestion
    const _targetFolders = await this.client.getAll(`spaces/${this.targetSpaceId}/stories`, {
```

2022-10-06 18:33 UTC, ademarCardoso commented on src/cli.js
> +  .option('--exclude-folders', 'Define which folders (slugs) should be excluded from sync. Separate with comma')
```suggestion
  .option('-e, --exclude-folders <FOLDER_NAME>', 'Define which folders (slugs) should be excluded from sync. Separate with comma')
```

2022-10-06 18:44 UTC, ademarCardoso requested changes
Thank you very much for the contribution my friend, @goran1023 .

I did some tests and it didn't work well, I got some error messages I think the feature is interesting and I think we can improve the code a bit. I noticed that there were some iterations of other users in your PR which makes the feature relevant 😄 , iI will talk to the team to analyze the feasibility of the feature.

2022-12-16 11:13 UTC, lisilinhart commented
Hi @goran1023 , would it be possible for you to reopen this PR  with the requested changes to  https://github.com/storyblok/storyblok-cli/? We're in the process of moving the code there and I can add your change by myself, but then your contribution would not be visible, so it would be better if you reopened it 🙂

2023-03-06 11:07 UTC, closed without merging